### ISSUE TITLE
Error occurred: Internal error: Invalid id 61f7072e-f809-4580-91ed-1d4439ef04f7

### ISSUE THREAD

**Issue by jesse234** [damianofalcioni/IP-Biter#10]
hi bro thanks for your response i was able to deploy ipbiter php and it opened up correctly , but i have a problem each time i try to save my configuration i get this error.
, Error occurred:
Internal error: Invalid id 61f7072e-f809-4580-91ed-1d4439ef04f7
 Are mine missing something here ? please help me out and thanks in advance

**Comment by jesse234** [comment]
thanks for the quick response , there are none just , Error occurred:
Internal error: Invalid id 61f7072e-f809-4580-91ed-1d4439ef04f7 from the uuid

**Comment by damianofalcioni** [comment]
please check if you have the write access to the configs and reports folders.
If this folders are not yet present, create them manually in the same folder of the PHP file and give write access.

**Comment by jesse234** [comment]
ok bro thanks

**Comment by jesse234** [comment]
hello bro i did all you asked , but i still have difficulties in using this , its a good work though but it is very complex to roll with and believe me most github users who is less knowledgeable about php would experience the same i have tried to fix the error for about 200 hours and i still cant find a clue , could you please come up with a configuration demo to be more specific and elaborate more on the lines in the php file to comment on ? but if you cant no problems i see the idea behind the tool but i cant use it , all thesame good job bro and thanks

**Comment by damianofalcioni** [comment]
Please post the XHR network requests and responses occurring after the save button click, or provide a public demo access to this critical deployment.
In order to analyze and try to replicate the problem also the PHP configuration will be useful, otherwise will be really difficult to find a solution
