### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andresdev16** [damianofalcioni/IP-Biter#12]
{"status" : -1, "error" : "op parameter not valid"}

**Comment by damianofalcioni** [comment]
https://github.com/damianofalcioni/IP-Biter#access-the-dashboard

> Access the Dashboard

> 1. Access the dashboard through ipb.php?op=$dashboardPage (or through ipb.php if $dashboardPage=='')
> - If $dashboardPageSecret!='' then a login page will appear asking for the $dashboardPageSecret value
