### ISSUE TITLE
Tool works, but the reports json is not loaded in the dashboard, although it logs users

### ISSUE THREAD

**Issue by thalst** [damianofalcioni/IP-Biter#13]
Hi, thanks for the great tool. 

My Application runs smoothly. Images can be seen on the links generated by the program. The only problem I'm having is the report not loading where it was supposed to be in the dashboard. But the logs are correct in the JSON. Do you have some insight on what could have gone wrong? I did no modification on your code, and nothing shows in error.log.

Thanks in advance,

Thiago

**Comment by damianofalcioni** [comment]
Hi Thiao, 
Try to check for some error in the browser console.
As you can see in the demo page http://ipbiter.rf.gd/?op=dashboard the dashboard works correctly and show the tracked viewers, so without more information on how replicate the error I cannot help you.

**Comment by XtremeCoder007** [comment]
I have the same issue, what can i do to resolve this ?
