### ISSUE TITLE
Internal error 

### ISSUE THREAD

**Issue by rmasiniexpert** [damianofalcioni/IP-Biter#14]
Dear Damiano, 

I generated the image url but when I tried to save the configuration in the dashboard, it always threw me an error message.

`
Error occurred:
Internal error: Invalid id 712b3f44-3244-4931-83f5-89cfb0eec439`

You can check it at:[ ec2-3-131-142-102.us-east-2.compute.amazonaws.com/IP-Biter/ipb.php?op=dashboard](ec2-3-131-142-102.us-east-2.compute.amazonaws.com/IP-Biter/ipb.php?op=dashboard)

System info: 

System:    Host: ----------------- Kernel: 5.4.0-1029-aws x86_64 bits: 64 Console: tty 0 
           Distro: Ubuntu 20.04.1 LTS (Focal Fossa) 
Machine:   Type: Xen System: Xen product: HVM domU v: 4.2.amazon serial: <superuser/root required> 
           Mobo: N/A model: N/A serial: N/A BIOS: Xen v: 4.2.amazon date: 08/24/2006 
CPU:       Topology: Single Core model: Intel Xeon E5-2676 v3 bits: 64 type: MCP L2 cache: 30.0 MiB 
           Speed: 2400 MHz min/max: N/A Core speed (MHz): 1: 2400 
Graphics:  Device-1: Cirrus Logic GD 5446 driver: N/A 
           Display: server: No display server data found. Headless machine? tty: 133x32 
           Message: Advanced graphics data unavailable in console. Try -G --display 
Audio:     Message: No Device data found. 
Network:   Device-1: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge driver: N/A 
           IF-ID-1: eth0 state: up speed: N/A duplex: N/A mac: 0a:d4:04:64:0c:e2 
Drives:    Local Storage: total: 8.00 GiB used: 2.10 GiB (26.3%) 
Partition: ID-1: / size: 7.69 GiB used: 2.10 GiB (27.4%) fs: ext4 dev: /dev/xvda1 
Sensors:   Message: No sensors data was found. Is sensors configured? 
Info:      Processes: 106 Uptime: 42m Memory: 978.6 MiB used: 229.6 MiB (23.5%) Init: systemd runlevel: 5 Shell: bash 
           inxi: 3.0.38

**Comment by damianofalcioni** [comment]
Duplicate of #10 

Please check if you have the write access rights to the 'configs' and 'reports' folders.
If this folders are not yet present, create them manually in the same folder of the PHP file and give write access rights.

Let me know if this fixed the error.

**Comment by rmasiniexpert** [comment]
Thanks.
I can create the folders, but how a given write access rights for them? May I ask how to do that?

**Comment by damianofalcioni** [comment]
First be sure to have created the folders in the IP-Biter directory, like this (adapt the directory if different):

`sudo mkdir /var/www/IP-Biter/configs`
`sudo mkdir /var/www/IP-Biter/reports`

Then it should be enough to change the owner of the folder to the user that run your apache/php, that should be `www-data` (adapt the user and the path of IP-Biter if different in your case):

`sudo chown -R www-data:www-data /var/www/IP-Biter/ `

**Comment by rmasiniexpert** [comment]
Perfectly worked.
Thanks for your always amazing support!
