### ISSUE TITLE
Tracking Reports are generated in reports folder but are not displayed in dashboard

### ISSUE THREAD

**Issue by XtremeCoder007** [damianofalcioni/IP-Biter#15]
Tracking Reports are generated in reports folder but are not displayed in dashboard

Anyway to resolve this ?

Kind regards,

XtremeCoder007

**Comment by damianofalcioni** [comment]
Hi,
is there any error in the error.log file or in the browser console?
Be sure also to have loaded the right "Track UUID" in order to visualize the associated reports.

**Comment by XtremeCoder007** [comment]
Nothing in the error.log nor in the console log except that the UUID will be defined as cross-site-cookie soon.
i can see the .json in config folder and a populated .json in the report folder it just doesnt seem to be fetched by the php and parsed.
check the div responsible that's all fine so not sure what the error is.

**I just noticed if i view it via microsoft edge it works fine, i was using mozilla firefox 86.0.1**

**Comment by damianofalcioni** [comment]
I tried right now the demo page ([http://ipbiter.rf.gd/?op=dashboard](http://ipbiter.rf.gd/?op=dashboard)) with Firefox 87 and it work correctly.
Maybe you have to click over the Tracking Report header bar to show the content, that at the beginning is collapsed.
Do you have the same problem also in the demo page?

**Comment by XtremeCoder007** [comment]
Yes i had the same issue, just now updated firfox to 87 still the same issue.
Now since it's working in another browser and it's not script-issue, it's not that urgent.
But if you want me to further investigate i'm happy todo so.

**Comment by damianofalcioni** [comment]
One check you can do in the browser inspection console is, after pressing the Load button in the dashboard, see if you have a network request starting with ?op=loadConfig&.... and check if inside this JSON response there is the trackList array filled (inside track).

Thanks for the support.

**Comment by damianofalcioni** [comment]
Maybe your problem is the self-tracking preventing feature.
Basically if you open the tracking links in the same browser of the dashboard, you will not be tracked. In order to test the tracking links you should open them in another browser or in an incognito window.
