### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by niladrishekhar** [damianofalcioni/IP-Biter#16]
These are the steps that I followed 
1. copied the files to /var/www/html/IP-Biter-master/
2. restart apache2
3. try 127.0.0.1/IP-Biter-master/ipb.php?op=$dashboardPage

I got an error message 	"op parameter not valid" when I look into the error log files - 
26/03/2021 12:03:41 127.0.0.1 op parameter not valid
26/03/2021 12:03:41 127.0.0.1 ERROR on line 0: Directive 'allow_url_include' is deprecated

i can understand that the issue is because I am using php 7.4 and the "allow_url_include" is not included in php 7.4.

What should be the alternative - I cant downgrade the php version as I am hosting a number of self hosted sites. and hence downgrading or using update-alternatives will be a challenge.

Also can you please help me understand - do I need to create folders with name "configs", "reports" in the folder or will they be created by the php file after first run? 
Also I dont see a .htaccess file - is this something I create or the php file creates it?

**Comment by damianofalcioni** [comment]
Hi,
when in the documentation I wrote $dashboardPage I meant the value of the PHP variable $dashboardPage, so "dashboard".
So the correct url in the default case is
127.0.0.1/IP-Biter-master/ipb.php?op=dashboard

**Comment by damianofalcioni** [comment]
allow_url_include is a deprecated setting in your PHP configuration file and not related with IP-Biter
