### ISSUE TITLE
Make anonym.to optional

### ISSUE THREAD

**Issue by ToeiRei** [damianofalcioni/IP-Biter#18]
First off - good work with your script; Would you mind making the anonymizer optional? That's a quick fix on the links not opening correctly.

**Comment by damianofalcioni** [comment]
Hi,
can you please send me a sample of link that do not open correctly? 
Anyway that's a good suggestion, I will make it optional in the setting on next release.
Thanks,
Damiano

**Comment by damianofalcioni** [comment]
in the meantime you can fix it simple leaving the variable _anonymRedirectService empty on [line 172](https://github.com/damianofalcioni/IP-Biter/blob/master/ipb.php#L172):
`_anonymRedirectService : '',`

**Comment by ToeiRei** [comment]
That's what I did for now as the links didn't open here at all having my URL and the anonym.to and the target as one string.

**Comment by damianofalcioni** [comment]
Thanks for the report. Indeed anonym.to look offline.

**Comment by ToeiRei** [comment]
oh. Didn't even check that as I usually just use a tails machine.

**Comment by damianofalcioni** [comment]
fixed here: https://github.com/damianofalcioni/IP-Biter/commit/af21cbb66cf41c161198e55d16f10c516e63cb18
