### ISSUE TITLE
auth via static link on dashboard

### ISSUE THREAD

**Issue by ToeiRei** [damianofalcioni/IP-Biter#19]
Would be nice to have something like an auth link so you could just log in using a bookmark as entering the password all the time slows down the process of analyzing things pretty significant

**Comment by damianofalcioni** [comment]
Hi,
does the browser password auto-filling feature not work?

**Comment by ToeiRei** [comment]
I am using the IP Biter in a semi automated environment. Links like https://bla?auth=somerandomstring are easier to implement

**Comment by damianofalcioni** [comment]
This is already possible passing the query parameter `secret`:
```
/ipb.php?op=dashboard&secret=_your_password_here_
```

**Comment by ToeiRei** [comment]
thanks - exactly what I need
