### ISSUE TITLE
HTTP Error 400 - Bad Request

### ISSUE THREAD

**Issue by benkhouya** [damianofalcioni/IP-Biter#2]
**Tracking doesn't work !**

All access to tracking links generated by your script return an HTTP Error 400, 
Also for image links.

error.log content :

> 
> 23/11/2017 05:33:09 141.101.104.X Invalid tid e33595fa-bd07-49bd-805b-7e5500b2006e
> 23/11/2017 05:34:10 141.101.104.X Invalid tid e33595fa-bd07-49bd-805b-7e5500b2006e
> 23/11/2017 05:35:25 141.101.104.X Invalid tid e33595fa-bd07-49bd-805b-7e5500b2006e

Config : Apache 2, PHP 5.6, ModSec2, PHP Handler tested : suPHP & CGI, Cloudflare.

-- YB

**Comment by damianofalcioni** [comment]
did you click on the save button before accessing the link?

**Comment by benkhouya** [comment]
Sorry I missed to click save, but now I have an HTTP Error 500 when I click on the tracking links.

You can try here : 
`https://emailfake.us/test/?op=dashboard`

**Comment by damianofalcioni** [comment]
there is something in the error.log?
Check if your environment have the mail function setted and if not try commenting the send mail operation at line 1252.

**Comment by benkhouya** [comment]
There is no error.log 
And the mail() function works fine on this environment, I will try to switch from suPHP to CGI, and retest.

PS. I've updated your script by commenting the mail() function in line 1209 & 1252

**Comment by damianofalcioni** [comment]
Let me know.
PS: you did not need to comment the mail() function for testing. It is skipped if you did not provide a mail address in the "Notification address @" text field

**Comment by benkhouya** [comment]
Unfortunately doesn't work, I still obtain the **HTTP Error 500**.

I've tested : 
- Without mail() function.
- With PHP 5.6 & PHP 7.0
- With PHP handler : CGI & suPHP
- With ModSec2 disabled.
- And finaly without .htaccess

**Comment by damianofalcioni** [comment]
You can try:
1) add this line to the .htaccess: php_value display_errors 1
2) put var_dump in the critical section in order to identify the function generating the error
3) capture the fatal error adding this at the beginning of the php section:
`function shutDownFunction() { 
    $error = error_get_last();
    if ($error['type'] === E_ERROR) { 
       var_dump($error);
    } 
}
register_shutdown_function('shutDownFunction');`

Let me know if you have news

**Comment by damianofalcioni** [comment]
Check the last commit [here](https://github.com/damianofalcioni/IP-Biter/commit/a9193c2fcac5344895173ddce9a4cff7f6605570)

**Comment by benkhouya** [comment]
Perfect,

The problem is now identified : the PHP function ini_set() is disabled on my server config, for security reasons.

error.log content :
```
23/11/2017 15:48:50 162.158.93.XX ERROR on line 115: ini_set() has been disabled for security reasons
23/11/2017 15:48:52 162.158.93.XX ERROR on line 115: ini_set() has been disabled for security reasons
23/11/2017 15:49:19 162.158.93.XX ERROR on line 115: ini_set() has been disabled for security reasons
23/11/2017 15:49:20 162.158.93.XX ERROR on line 115: ini_set() has been disabled for security reasons
23/11/2017 15:49:20 162.158.93.XX ERROR on line 115: ini_set() has been disabled for security reasons
23/11/2017 15:49:21 162.158.93.XX ERROR on line 115: ini_set() has been disabled for security reasons
23/11/2017 15:49:21 162.158.93.XX ERROR on line 115: ini_set() has been disabled for security reasons
23/11/2017 15:49:30 162.158.93.XX ERROR on line 1257: Uncaught Error: Call to undefined function getallheaders() in /home/user/public_html/test/ipb.php:1257
Stack trace:
#0 {main}
  thrown
23/11/2017 15:49:31 162.158.93.XX ERROR on line 115: ini_set() has been disabled for security reasons

```

**Comment by damianofalcioni** [comment]
The problem here is not the ini_set (I added this in the last commit and you can comment it) but is the undefined function getallheaders in your environment.
Details here: [http://php.net/manual/en/function.getallheaders.php](http://php.net/manual/en/function.getallheaders.php)

**Comment by benkhouya** [comment]
I've disabled PHP-FPM for the domain where I host your script to fix the malfunction of getallheaders, and I've commented ini_set() in your script.

But now I've got the HTTP Error 404, with the log below : 

`[23-Nov-2017 16:40:29 UTC] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0`

**Comment by damianofalcioni** [comment]
Have a look at the last commit [here](https://github.com/damianofalcioni/IP-Biter/commit/baab494e0440d89c4de56af820a6d8ffecd08e45)
- ini_set fixed
- getallheaders fixed

**Comment by benkhouya** [comment]
I still got the **HTTP Error 404** with the tracking link, but not with the tracking image.

error_log : 
`[23-Nov-2017 19:33:13 UTC] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0`

And in the 2 cases, using the simple tracking link and the tracking image now I can receive the notification by email.

But nothing in the tracking reports, you can test with the link below : 
`https://emailfake.us/test/ipb.php?op=dashboard&uuid=4cb63eea-f660-4339-8912-0cd4819a855f`

Thank you for your efforts :-)

**Comment by damianofalcioni** [comment]
Have you changed something in my code? Because I did not use $HTTP_RAW_POST_DATA at all so is very strange that this message appear.
Please keep in mind that if you open a tracking link/image in the same browser where the dashboard is opened you did not get tracked (tracking prevention feature). You need to use another browser or the incognito mode.
It is strange that you receive the mail but did not see the log in the dashboard. Nothing regarding this in the log?

**Comment by benkhouya** [comment]
I've changed nothing in the code, but now the tracking reports works fine on Edge, Firefox and Chrome (in incognito mode, in my case) I have something in extensions that blocks the display of the tracking reports details, I'll try to identify it.

But I have a question : is it normal all browsers returns the **HTTP Error 404** by clicking directly on the tracking link ? Knowing that the tracking image returns correctly the defined image with the HTTP code 200, and in the both cases reports works.

And if possible, I have some recommandations :
- Change the color for the button "save" to catch the eye of users.
- Add the ability to define the sender mail in the source code (for reports), to avoid emails from username@hostname (or nobody, etc)
- In the mail reports if X-Forwarded-For (or Cf-Connecting-Ip) has an IP address, display this IP address not the IP address of the proxy/CDN, this is usefull if your script is hosted on a website behind Cloudflare for example.

**Comment by damianofalcioni** [comment]
Thanks for the suggestions, I will have a look on them.
About the 404 Page, Yes, if you did not provide a link where to be redirected (in the textbox that appear when add a new link), the link return a 404 page (but still track the user)

**Comment by benkhouya** [comment]
A big thank you.
