### ISSUE TITLE
Overview of all links

### ISSUE THREAD

**Issue by ToeiRei** [damianofalcioni/IP-Biter#22]
Would it be possible to get an overview over all links generated with a link to those 'dashboard overviews' for easier access?

**Comment by damianofalcioni** [comment]
Hi,
this would require a user profiling that is currently not implemented. This could be a side project that use a SSO like Keycloak to solve also #19, but currently I have no time plans to implement it.

**Comment by ToeiRei** [comment]
I would just go for the all-on-instance view as I use it for scambaiting as grabify and friends are by now 'well known'

**Comment by damianofalcioni** [comment]
Yes, showing all configurations will be possible and quite easy to do in a password protected admin ui.

**Comment by damianofalcioni** [comment]
implemented in https://github.com/damianofalcioni/IP-Biter/commit/60dcc07ff14ded3fafc389e8db787a5765b22b7b
