### ISSUE TITLE
IPV4

### ISSUE THREAD

**Issue by s0517798** [damianofalcioni/IP-Biter#25]
"I find the script very useful. However, I have a few questions. It seems that the script cannot retrieve IPV4. I only see the IPV6 result returned. In the next release, could you adjust the script? Another issue is that I want to retrieve the IP's Port as well. Please help me with this."

Let me know if you need further assistance!

**Comment by damianofalcioni** [comment]
Hi,
to return the remote port (that btw is autogenerated, so not much useful), you can change lines:
https://github.com/damianofalcioni/IP-Biter/blob/60dcc07ff14ded3fafc389e8db787a5765b22b7b/ipb.php#L1555
and
https://github.com/damianofalcioni/IP-Biter/blob/60dcc07ff14ded3fafc389e8db787a5765b22b7b/ipb.php#L1601

to 
`ip' => $_SERVER['REMOTE_ADDR'] . ':' . $_SERVER['REMOTE_PORT'],`


To convert the $_SERVER['REMOTE_ADDR'] from IPV6 to IPV4 you can preprocess this value before returning it using the method described here: https://stackoverflow.com/questions/12435582/php-serverremote-addr-shows-ipv6

**Comment by s0517798** [comment]
The service provider's IP is NATted so I need the port to trace it.
When I access whatismyip, I see that it collects both ipv4 and ipv6. Why when tracking, it only gets 1 type of ip?

**Comment by damianofalcioni** [comment]
Hi,
as https://letmegooglethat.com/?q=php+retrieve+client+both+ipv4+and+ipv6 suggest, you cannot have both ip collected in a single request. It depend how you expose the server, or better how the client reach your server. 
If the client reach your ipv4 server address, the collected client ip will be in ipv4 format. 
if the client reach your ipv6 server address, the collected client ip will be in ipv6 format.
if the client reach first your dns, then depends on how the dns resolve your ip, if ipv4 or ipv6.
So I guess services like whatsmyip will perform two client request to different servers (ipv4 and ipv6 exposed) and combine the results.

**Comment by damianofalcioni** [comment]
Hi as https://googlethatforyou.com?q=php%20retrieve%20client%20both%20ipv4%20and%20ipv6 suggest, you cannot have both ipv4 and ipv6 collected with a single client request. The ip format collected depends the way your server is exposed, or better, how the client reach your server.
If the client send a request to your ipv4 address, the client ipv4 address will be collected.
If the client send a request to your ipv6 address, the client ipv6 address will be collected.
If the client send a request to your dns, then depends on how the dns resolve your ip if, ipv4 or ipv6.
So I guess services like whatsmyip will perform 2 client requests, one to an ipv4 server and one to an ipv6 server and then combine the results.

**Comment by s0517798** [comment]
I have trouble displaying when editing the code according to your instructions.
For example: When capturing the IP address => Whois, the link will redirect to https://example.com/ip:port
The owner information is not displayed.

**Comment by damianofalcioni** [comment]
you right, all this analysis function work only with IP, so or you split the string on : before passing it as a quick fix.
When I'll have time will work on a more elegant solution storing the port in a separate json key and showing it in the dashboard as a separate field near the remote ip

**Comment by s0517798** [comment]
thank you. i wait for your help.

**Comment by damianofalcioni** [comment]
solved here https://github.com/damianofalcioni/IP-Biter/commit/5a0c30bdc6a2b83d74811bef42d78e1da5b09c19

**Comment by s0517798** [comment]
The problem has been resolved. Thank you so much!

**Comment by s0517798** [comment]
I got an error
`Error occurred:
Error contacting the service: /ipb.php?op=ipwhois&ip=15.235.162.58 : error`
