### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by s0517798** [damianofalcioni/IP-Biter#27]
Can you give a visual guide on how to add a telegram bot? I followed the instructions but it didn't work.

**Comment by s0517798** [comment]
After entering bot_token and bot_id into ibp.php file and IP trap link. I see Bot is working.
But the returned information is missing a lot of data especially IP port. Can you make it more complete?

**Comment by damianofalcioni** [comment]
The idea is that this is just a notification, exactly like the mail, that's why there is a link to the dashboard to check the full details. I could add the port, but not all the http headers or whois infos.

**Comment by s0517798** [comment]
For some special reasons. Can you help me configure getting time up to microsecond?

**Comment by damianofalcioni** [comment]
should be enough to change lines https://github.com/damianofalcioni/IP-Biter/blob/d08b349840e599e0ef9a70884016f1101a6bcf49/ipb.php#L1695
and 
https://github.com/damianofalcioni/IP-Biter/blob/d08b349840e599e0ef9a70884016f1101a6bcf49/ipb.php#L1738
to:

```php
'time'=>date("d-m-Y H:i:s.").gettimeofday()["usec"],
``` 
please, next time open a new issue.

**Comment by s0517798** [comment]
Thank you very much
