### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by s0517798** [damianofalcioni/IP-Biter#28]
I got a 400 error when applying the instructions

https://github.com/damianofalcioni/IP-Biter/issues/27#issuecomment-2425843088

Specific error: When I use the original browser to create the trap link, it is accessible normally. When sending it to others or using another browser, it will get a 400 error.

**Comment by s0517798** [comment]
Help me

**Comment by damianofalcioni** [comment]
Hi,
what is the browser that work and the one who fail?
Does this happen also without the changes to microtime ?
There are more detailed errors in the log file?

**Comment by s0517798** [comment]
For example: I use Chrome browser to create a trap link. I immediately access that link and it works. If I close the browser and open the trap link, it will report error 400.

**Comment by damianofalcioni** [comment]
I updated my answer: https://github.com/damianofalcioni/IP-Biter/issues/27#issuecomment-2425843088
Please check. This code should now work.

**Comment by s0517798** [comment]
It worked. Thank you very much.
