### ISSUE TITLE
Dashboard not accessable

### ISSUE THREAD

**Issue by H4xl0r** [damianofalcioni/IP-Biter#3]
Got an Apache2 server running on the latest Kali Linux.
Uploaded the ipb.php to the webserver and added the .htaccess file.
When i browse to the site (ipb.php) it gives me the error ::
{"status" : -1, "error" : "op parameter not valid"}

also when browsing to ::
ipb.php?op=$dashboardPage 

same error 

are there some more Settings to be set for the server ? additional modules or so ?
please give more Information about the Server settings please, it is not running directly...
i am using a ssl cert from https://letsencrypt.org/ with some security settings .....

**Comment by embutidox** [comment]
Same error here, but without letsencrypt.

**Comment by H4xl0r** [comment]
Ok so now we know it is not the https://letsencrypt.org/ ssl cert and their Settings, are there some Settings to set on the php.conf ?

**Comment by damianofalcioni** [comment]
When I wrote ipb.php?op=$dashboardPage I meant $dashboardPage as PHP variable...so if you look in the head of the PHP code you will see that $dashboardPage = dashboard so accesso  ipb.php?op=dashboard
Note that if you would like to visualize the dashboard on the ipb.php access you can just leave the variable $dashboardPage="".
Have a look at the DEMO!

**Comment by H4xl0r** [comment]
Perfect Worked thanks so .... to Link to Dash is ipb.php?op=dashboard

WORKS

**Comment by H4xl0r** [comment]
I can access the Dash now, nice....
but it does not write files to the Folder, the generated settings are not saved.
and the reload goes to an error 
Error occurred:
Internal error: Invalid id 2d2c7ca7-45b1-4cee-9f4c-b966c4b96973

Even running it with chmod 777 is not making the trick.

**Comment by damianofalcioni** [comment]
there is something about that in the error.log file?

**Comment by H4xl0r** [comment]
there is no error.log file , he is not writing anything to the folders.
even changing users to www-data and give permissions.... is not changing the behavior 
could it be because it located under /var/www/SUBFOLDER?

**Comment by H4xl0r** [comment]
OK solved it by giving right permissions 
sorry for the work all working fine now.
nice work.
