### ISSUE TITLE
Generate UUID/trackUUID with GET

### ISSUE THREAD

**Issue by benkhouya** [damianofalcioni/IP-Biter#7]
Hi,
Can you add a piece of code to generate UUID/trackUUID using **GET** method, with the possibility to set some data directly in URI, like :

`/ipb.php?op=dashboard&notificationemail={EMAIL}&trackimage={IMAGE}`

The page can return the generated UUID, trackUUID, etc and stores each variable value in PHP variables, for further handling.

This change can help to integrate your script with existing projects.
Thanks.

**Comment by damianofalcioni** [comment]
Thanks, I will take into account your suggestion.
In the meanwhile you can create a tracking image and link posting the configuration json in the operation "save". In particular:
POST /ipb.php?op=save
POST data:
`{
	"uuid": "d5a88dcc-7d84-46ac-80a8-f631bb7ed024",
	"trackUUID": "e765714e-bef4-47ef-910a-bdf8a75f388a",
	"trackingEnabled": true,
	"mailId": "",
	"notificationAddress": "",
	"trackingImage": "",
	"trackingImageStatusCode": 200,
	"trackingImageCustomHeaderList": ["Content-Type: image/png", "Cache-Control: no-store, no-cache, must-revalidate, max-age=0", "Cache-Control: post-check=0, pre-check=0", "Pragma: no-cache", "Expires: 0", "P3P: CP=\"OTI DSP COR CUR IVD CONi OTPi OUR IND UNI STA PRE\""],
	"trackingImageGeneratedUrl": "http://ipbiter.rf.gd/?op=i&tid=e765714e-bef4-47ef-910a-bdf8a75f388a",
	"trackingImageShortUrl": "",
	"trackingLinks": {
		"7f3f25f6-8954-4fb4-a1b1-4deeec1097a3": {
			"original": "",
			"generated": "http://ipbiter.rf.gd/?op=l&tid=e765714e-bef4-47ef-910a-bdf8a75f388a&lid=7f3f25f6-8954-4fb4-a1b1-4deeec1097a3",
			"shortened": ""
		}
	}
}
`

being careful to change the UUID and trackUUID with randomly generated IDs, and adapting the trackingImageGeneratedUrl and trackingLinks/generated with the previously generated trackingUUID
