### ISSUE TITLE
redirect after view

### ISSUE THREAD

**Issue by johnjohny1990** [damianofalcioni/IP-Biter#9]
hi my friends
i wana after view by target after 5 second redirect to another url and they see real site (after get cookie)
can i help me

**Comment by johnjohny1990** [comment]
for example 
where i do add this code ?
header("Refresh: 5; URL=http://google.com");

**Comment by damianofalcioni** [comment]
this is the line that perform the redirect:
https://github.com/damianofalcioni/IP-Biter/blob/76aee10cc03f2a4be115a55178f3c1a1e4153d7a/ipb.php#L1342

**Comment by johnjohny1990** [comment]
Hi
I said "hi my friends
i wana after view by target after 5 second redirect to another url and they see real site (after get cookie)"
you said "  header('Location: '.$redirectToUrl); " 
i dont understand
how do i do it?

**Comment by damianofalcioni** [comment]
Hi,
when you click the "Create Tracking Link" button there will appear a text field where is written "add the original url here". There you can write google.com and the user will be tracked and redirected to google.com.
Bye

**Comment by johnjohny1990** [comment]
Hi
no this is for continue for my website when I add the original the url here fro example : www.google.com but appear this 
....
127.0.0.1/www.google.com



Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404
127.0.0.1
Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.3.6
....
I wanna redirect to google.com

**Comment by johnjohny1990** [comment]
thank 
sorry I dident see it

**Comment by damianofalcioni** [comment]
just put http://www.google.com. Only google.com may not work
